apiVersion: v1
kind: Service
metadata:
  name: configmaps-example-preview
spec:
  type: ClusterIP
  selector:
    app: configmaps-example
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080